format = "$hostname$directory$git_branch\n$character"

[hostname]
ssh_only = false
style = "bold green"
format = "[$hostname::]($style)"

[directory]
truncation_length = 1
style = "bold cyan"
format = "[$path]($style) "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style)"
style = "bold italic red"

[character]
success_symbol = "[❯](cyan)"
error_symbol = "[✗](cyan)"